name: build-and-push-image

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest # 14-GB disk now sufficient
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true # upload to GHCR
          outputs: type=registry # ← NO local load = ½ disk
          provenance: false # disable 100-MB attestation layer  [oai_citation:3‡GitHub](https://github.com/docker/buildx/issues/1714?utm_source=chatgpt.com)
          sbom: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha # small metadata cache
          cache-to: type=gha,mode=max

      - name: fish-speech --help
        run: docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest fish-speech --help
